// <auto-generated />
namespace TravelPlanner.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newitinitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newitinitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201808281454029_new itin item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
